### ISSUE TITLE
【提问】请问作者博客的引擎和主题是什么

### ISSUE THREAD

**Issue by Zhang21** [iuxt/quickstart#2]
看到作者的博客，主题界面挺好看的，想参考一下主题和配置替换下我自己的博客。

我这面hexo或hugo都可以，谢谢。

**Comment by iuxt** [comment]
我有两个网站，
1. https://zahui.fan    这个是hexo + butterfly主题
2. https://babudiu.com   这个是halo + joe 2.0主题

**Comment by Zhang21** [comment]
阿里嘎多
